import { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { Search, Star, GitFork, ChevronLeft, ChevronRight } from 'lucide-react';
import { motion } from 'framer-motion';

const API = process.env.REACT_APP_BACKEND_URL;

export default function Browse() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [reports, setReports] = useState([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState(searchParams.get('search') || '');
  const page = parseInt(searchParams.get('page') || '1');
  const navigate = useNavigate();

  useEffect(() => {
    fetchReports();
  }, [searchParams]);

  const fetchReports = async () => {
    setLoading(true);
    try {
      const q = searchParams.get('search') || '';
      const p = searchParams.get('page') || '1';
      const res = await fetch(`${API}/api/reports?search=${encodeURIComponent(q)}&page=${p}&limit=12`);
      const data = await res.json();
      setReports(data.reports || []);
      setTotal(data.total || 0);
    } catch {
      setReports([]);
    }
    setLoading(false);
  };

  const handleSearch = (e) => {
    e.preventDefault();
    setSearchParams({ search, page: '1' });
  };

  const totalPages = Math.ceil(total / 12);

  return (
    <div className="min-h-[calc(100vh-4rem)] px-6 py-8">
      <div className="max-w-7xl mx-auto">
        <div className="mb-8">
          <p className="text-sm text-muted-foreground tracking-widest uppercase font-mono mb-1">Explore</p>
          <h1 className="text-3xl md:text-5xl font-heading font-bold tracking-tight">Browse Reports</h1>
          <p className="text-base text-muted-foreground mt-2">
            {total} report{total !== 1 ? 's' : ''} generated by the community. All free to read.
          </p>
        </div>

        <form onSubmit={handleSearch} className="mb-8 max-w-xl">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="Search by repo name, language, or description..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-10 h-11 bg-muted/50 border-transparent focus:border-primary"
              data-testid="browse-search-input"
            />
          </div>
        </form>

        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {Array.from({ length: 6 }).map((_, i) => (
              <Skeleton key={i} className="h-40" />
            ))}
          </div>
        ) : reports.length === 0 ? (
          <div className="text-center py-20" data-testid="no-reports-message">
            <p className="text-lg text-muted-foreground">No reports found</p>
            <p className="text-sm text-muted-foreground mt-1">Be the first to generate one!</p>
            <Button className="mt-4 bg-primary text-primary-foreground" onClick={() => navigate('/')}>
              Generate a Report
            </Button>
          </div>
        ) : (
          <>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {reports.map((report, i) => (
                <motion.div
                  key={report.id}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.03 }}
                >
                  <Card
                    className="bg-card/50 backdrop-blur-md border-border/50 hover:border-primary/30 transition-all duration-300 cursor-pointer group h-full"
                    onClick={() => navigate(`/report/${report.id}`)}
                    data-testid={`browse-report-${report.id}`}
                  >
                    <CardContent className="p-5 flex flex-col h-full">
                      <div className="flex items-start justify-between mb-2">
                        <h3 className="font-heading font-semibold text-foreground group-hover:text-primary transition-colors truncate pr-2 text-sm">
                          {report.repo_full_name}
                        </h3>
                        {report.language && (
                          <Badge variant="secondary" className="text-[10px] shrink-0">{report.language}</Badge>
                        )}
                      </div>
                      <p className="text-sm text-muted-foreground line-clamp-2 flex-1">
                        {report.description || 'No description available'}
                      </p>
                      <div className="flex items-center gap-4 text-xs text-muted-foreground mt-3 pt-3 border-t border-border/50">
                        <span className="flex items-center gap-1"><Star className="w-3 h-3" /> {report.stars?.toLocaleString() || 0}</span>
                        <span className="flex items-center gap-1"><GitFork className="w-3 h-3" /> {report.forks?.toLocaleString() || 0}</span>
                        <span className="ml-auto">v{report.version || 1}</span>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>

            {/* Pagination */}
            {totalPages > 1 && (
              <div className="flex items-center justify-center gap-2 mt-8">
                <Button variant="outline" size="sm" disabled={page <= 1}
                  onClick={() => setSearchParams({ search, page: String(page - 1) })} data-testid="prev-page">
                  <ChevronLeft className="w-4 h-4" />
                </Button>
                <span className="text-sm text-muted-foreground px-3">
                  Page {page} of {totalPages}
                </span>
                <Button variant="outline" size="sm" disabled={page >= totalPages}
                  onClick={() => setSearchParams({ search, page: String(page + 1) })} data-testid="next-page">
                  <ChevronRight className="w-4 h-4" />
                </Button>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
